import linkbot3 as linkbot
import math
import time

# Change your robot name here
mel = linkbot.CLinkbot("JKDV") 
ten = linkbot.CLinkbot("1H6R")
bass = linkbot.CLinkbot("B38D")

tempo = 72
beat = 60./tempo
art = beat * .03

freq = {"A440":440, 'R': 0, '':0, 'C':440*2**(3/12), 'C#':440*2**(4/12), 'Db':440*2**(4/12), 'D':440*2**(5/12), 'D#':440*2**(6/12), 'Eb':440*2**(6/12), 'E':440*2**(7/12), 'E#':440*2**(8/12), 'F':440*2**(8/12), 'F#':440*2**(9/12), 'Gb':440*2**(9/12), 'G':440*2**(10/12), 'G#':440*2**(11/12), 'Ab':440*2**(11/12), 'A':440*2**(12/12), 'A#':440*2**(13/12), 'Bb':440*2**(13/12), 'B':440*2**(14/12), 'Fb':440*2**(7/12), 'B#':440*2**(3/12)}
octv = {-1 : -1-5, 0 : 0-5, 1 : 1-5, 2 : 2-5, 3 : 3-5, 4 : 4-5, 5 : 5-5, 6 : 6-5, 7: 7-5, 8: 8-5, 9: 9-5, 10: 10-5, 11: 11-5,}

#1
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#2
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#3
bass.buzzer.set_frequency(freq['A'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#4
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3-.05 * beat)
bass.buzzer.set_frequency(0)
time.sleep(.05 * beat)

bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#5
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#6
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#7
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)


bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#8
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#9
bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#10
bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)


#11
bass.buzzer.set_frequency(freq['D'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#12
bass.buzzer.set_frequency(freq['C'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['A#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)


#13
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#14
bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#15
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)


#16
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['C'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#17
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#18
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['C'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#19
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#20
bass.buzzer.set_frequency(freq['E#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#21
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#22
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

#23
bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[1]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#24
bass.buzzer.set_frequency(freq['E#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#25
bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['D#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#26
bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[1]))
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#27
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#28
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#29
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(0)
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#30
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#31
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(0)
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

#32
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

#33
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#34
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

#35
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[6]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[6]))
time.sleep(1/3 * beat)

#36
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[6]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#37
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

#38
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

#39
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['D'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

#40
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['A'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#41
bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#42
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#43
bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#44
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#45
bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['B'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

#46
bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#47
bass.buzzer.set_frequency(freq['D#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#48
bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['D#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#49
bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

#50
bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['D'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#51
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#52
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['D'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#53
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#54
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['D'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#55
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#56
bass.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['B'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['B'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#57
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['D#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#58
bass.buzzer.set_frequency(freq['A'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['F#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#59
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

#60
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#61
bass.buzzer.set_frequency(freq['B#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#62
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#63
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[1]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#64
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[5]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#65
bass.buzzer.set_frequency(freq['G#'] * 2 ** (octv[1]))
ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[5]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['D#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['A'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['B#'] * 2 ** (octv[4]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['F#'] * 2 ** (octv[3]))
time.sleep(1/12 * beat)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/4 * beat - art)
mel.buzzer.set_frequency(0)
time.sleep(art)

#66
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(0)
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[4]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

#67
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(0)
mel.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)

bass.buzzer.set_frequency(0)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
mel.buzzer.set_frequency(0)
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)

ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)
ten.buzzer.set_frequency(freq['E'] * 2 ** (octv[2]))
time.sleep(1/3 * beat)

#68
ten.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
time.sleep(2 * beat)
ten.buzzer.set_frequency(0)
time.sleep(.1 * beat)

bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))


time.sleep(2 * beat)
bass.buzzer.set_frequency(0)
ten.buzzer.set_frequency(0)
mel.buzzer.set_frequency(0)
time.sleep(.125 * beat)

#69
bass.buzzer.set_frequency(freq['C#'] * 2 ** (octv[2]))
ten.buzzer.set_frequency(freq['G#'] * 2 ** (octv[2]))
mel.buzzer.set_frequency(freq['C#'] * 2 ** (octv[3]))
time.sleep(4 * beat)



#turn everything off at the end
mel.buzzer.set_frequency(0)
ten.buzzer.set_frequency(0)
bass.buzzer.set_frequency(0)

